language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
  - tar zvfx cmake-3.5.2-Linux-x86_64.tar.gz
  - ./cmake-3.5.2-Linux-x86_64/bin/cmake ..
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
script:
  - make
  - ./unittests/all_unittests
