language: cpp
compiler: gcc

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          config:
             retries: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          config:
             retries: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          config:
             retries: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - pip install --user --upgrade pip
  - sudo apt-get install lcov
  - pip install --user cpp-coveralls

before_script:
  - cmake -DCODE_COVERAGE=1 .

script:
  - make -j2
  - ./unittests/all_unittests

after_success:
  - coveralls --include src --include include --gcov-options '\-lp'
