sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang

before_script:
  - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
  - tar zvfx cmake-3.5.2-Linux-x86_64.tar.gz
  - ./cmake-3.5.2-Linux-x86_64/bin/cmake -DCODE_COVERAGE=1 .

install:
  - sudo apt-get install lcov
  - pip install --user cpp-coveralls

script:
  - make
  - ./unittests/all_unittests

after_success:
  - coveralls --include src --include include --gcov-options '\-lp'
